### ISSUE TITLE
`#',a -> ECLECTOR.READER:UNQUOTE-IN-INVALID-CONTEXT

### ISSUE THREAD

**Issue by kpoeck** [s-expressionists/Eclector#59]
e.g. in sbcl
```lisp
(ql:quickload :eclector)
(eclector.reader:read-from-string "`#',a")

debugger invoked on a ECLECTOR.READER:UNQUOTE-IN-INVALID-CONTEXT in thread
#<THREAD "main thread" RUNNING {10004F04C3}>:
  Unquote is illegal in the function reader macro.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RECOVER] Read the following form as if it were not unquoted.
  1: [ABORT  ] Exit debugger, returning to top level.

(ECLECTOR.BASE:%READER-ERROR #<SB-IMPL::STRING-INPUT-STREAM {10048DDCB3}> ECLECTOR.READER:UNQUOTE-IN-INVALID-CONTEXT :SPLICING-P NIL :CONTEXT ECLECTOR.READER::SHARPSIGN-SINGLE-QUOTE)
   source: (APPLY #'ERROR DATUM :STREAM STREAM :STREAM-POSITION STREAM-POSITION
                  (ALEXANDRIA.0.DEV:REMOVE-FROM-PLIST ARGUMENTS
                                                      :STREAM-POSITION))
````

**Comment by kpoeck** [comment]
This idiom is widely used. I claso I found until now 13 files. While I can change that in clasp, it also happens in other libraries in the quicklisp universe and it seems not possible to change all exiing libraries.

First example https://gitlab.common-lisp.net/alexandria/alexandria/blob/master/functions.lisp#L157

See also in the discussion - you were part - in #clasp

**Comment by kpoeck** [comment]
I believe the workaround posted by scymtym is:
```lisp
(defun sharpsign-single-quote (stream char parameter)
  (declare (ignore char))
  (unless (null parameter)
    (numeric-parameter-ignored stream 'sharpsign-single-quote parameter))
  (let ((name (with-forbidden-quasiquotation ('sharpsign-single-quote :keep :keep #+(or) t)
                (read stream t nil t))))
    (if *read-suppress*
        nil
        `(function ,name))))
````

**Comment by kpoeck** [comment]
@scymtym what about making this configurable if you don't want to change that globally?

**Comment by scymtym** [comment]
Maybe by having a "relaxed" version of the reader macro function?

The best way forward would be deriving the correct behavior from the specification, of course.

**Comment by kpoeck** [comment]
How would I use the relaxed version?

**Comment by scymtym** [comment]
> How would I use the relaxed version?

You would install the relaxed version of the reader macro function into your readtable object.

Under the current circumstances, I can't promise that I will be able to work on this anytime soon. I suggest carrying on with the workaround in https://github.com/s-expressionists/Eclector/issues/59#issuecomment-601390652 for now.

**Comment by kpoeck** [comment]
There is no short term pressure to do this, so whenver you have time. I think now I understood what you are saying and could even do a PR implementing what you said.

Installing in the read-table seems easy enough, that I can do in clasp by myself
