### ISSUE TITLE
(read-from-string "#c ( #xF #o-1 ) ") not allowed in eclector

### ISSUE THREAD

**Issue by kpoeck** [s-expressionists/Eclector#70]
Hello,
looking at the spec in http://www.lispworks.com/documentation/HyperSpec/Body/02_dhk.htm it is simply said that:

#C reads a following object, which must be a list of length two whose elements are both reals. 

I don't see that "a following object" disallows the space.

See also:
https://github.com/sharplispers/parse-number/issues/9

Would be fine If we just could customize eclector not to signal an exception here

**Comment by scymtym** [comment]
I agree that the description sounds as if whitespace is fine, but there are some unclear aspects:

* The printed representation is described without optional whitespace:
  > 22.1.3.1.4 Printing Complexes
  > 
  > A complex is printed as #C, an open parenthesis, the printed representation of its real part, a space, the printed representation of its imaginary part, and finally a close parenthesis.
* [Sharpsign S](http://www.lispworks.com/documentation/HyperSpec/Body/02_dhm.htm) which has a similar structure is specified in a different way which suggests that whitespace is not accepted. SBCL, for example, indeed does not accept whitespace after `#S`.
* Interpreting "a following object" as skipping over non-objects would also make `#C #|foo|# (1 2)` legal (and SBCL, for example, indeed accepts it). Such an input would lead to a strange concrete syntax tree.

So maybe the best solution is customizable behavior as you suggest.

**Comment by scymtym** [comment]
Also: https://irclog.tymoon.eu/freenode/sicl?around=1600324357#1600324357
