### ISSUE TITLE
diagrams in eclector documentation don't fit the page

### ISSUE THREAD

**Issue by informatimago** [s-expressionists/Eclector#74]
For example:
<img width="1024" alt="Screenshot 2021-06-07 at 19 37 18" src="https://user-images.githubusercontent.com/791692/121064433-e0457600-c7c7-11eb-87a5-765491301058.png">

**Comment by scymtym** [comment]
Thanks for the report.

Last time I tried to fix this, I couldn't get both the HTML and PDF versions to work properly at the same time. This time, centering and scaling the images seems to have fixed the PDF version without causing problems for the HTML version.
